facility field removed in favor of facilities
```
Error: packet_device.libvirt: "facilities": required field is not set

Error: packet_device.libvirt: "facility": [REMOVED] Use the "facilities" array instead, i.e. change
  facility = "ewr1"
to
  facilities = ["ewr1"]
```